name: Scheduled & Manual Playwright Tests

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Create .env file
        run: |
          echo "DEFAULT_PASSWORD=${{ secrets.DEFAULT_PASSWORD }}" >> .env
          echo "BASE_URL=${{ secrets.BASEURL }}" >> .env
          echo "BASEURL_API=${{ secrets.BASEURL_API }}" >> .env
          echo "API_ENDPOINT_LOGIN=${{ secrets.API_ENDPOINT_LOGIN }}" >> .env        

      - name: Run Playwright tests
        run: npx playwright test
        env:
          CI: true
          DEFAULT_PASSWORD: ${{ secrets.DEFAULT_PASSWORD }}
          BASEURL: ${{ secrets.BASEURL }}
          BASEURL_API: ${{ secrets.BASEURL_API }}
          API_ENDPOINT_LOGIN: ${{ secrets.API_ENDPOINT_LOGIN }}

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Publish test results
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: Playwright Test Results
          path: test-results/junit.xml
          reporter: java-junit
